name: Update badges from credly site

on:
  workflow_dispatch:
  schedule:
    - cron: "10 0 */1 * *"
  pull_request:

jobs:
  update-readme:
    name: Update Readme with badges from credly
    runs-on: ubuntu-latest
    steps:
      - name: Update Readme with badges from credly
        uses: pemtajo/badge-readme@2.4.0
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMIT_MESSAGE: "Update badges from credly"
          CREDLY_USER: gurdip-sira
          CREDLY_SORT: POPULAR
