name: Sync Credly Badges

on:
  schedule:
    - cron: "0 6 * * *"   # daily
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch Credly badges
        run: |
          python scripts/credly.py

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: sync Credly certifications"
